/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/odds/mlb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mlb Odds */
        get: operations["get_mlb_odds_api_odds_mlb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/props/mlb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mlb Props */
        get: operations["get_mlb_props_api_props_mlb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picks/mlb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mlb Picks */
        get: operations["get_mlb_picks_api_picks_mlb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fetcher/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_fetcher_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fetcher/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_api_fetcher_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_refresh__event_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookPrice */
        BookPrice: {
            /** Bookmaker Key */
            bookmaker_key: string;
            /** Price American */
            price_american: number;
            /** Point */
            point?: number | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /** FetcherControlResponse */
        FetcherControlResponse: {
            /** Status */
            status: string;
            /** Tiers */
            tiers?: string[];
            /** Retry After Seconds */
            retry_after_seconds?: number | null;
            /** Event Id */
            event_id?: string | null;
            /** Polled */
            polled?: string[];
        };
        /** FetcherStatus */
        FetcherStatus: {
            /** Last Fetch At */
            last_fetch_at?: string | null;
            /** Requests Used */
            requests_used?: number | null;
            /** Requests Remaining */
            requests_remaining?: number | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Fetcher Running
             * @default false
             */
            fetcher_running: boolean;
            /** Enabled Tiers */
            enabled_tiers?: string[];
        };
        /** Game */
        Game: {
            /** Event Id */
            event_id: string;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /**
             * Commence Time
             * Format: date-time
             */
            commence_time: string;
            /**
             * Is Live
             * @default false
             */
            is_live: boolean;
            /** Markets */
            markets: components["schemas"]["Market"][];
            /**
             * Stale Seconds
             * @default 0
             */
            stale_seconds: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Market */
        Market: {
            /** Market Key */
            market_key: string;
            /** Outcomes */
            outcomes: components["schemas"]["MarketOutcome"][];
        };
        /** MarketOutcome */
        MarketOutcome: {
            /** Outcome Name */
            outcome_name: string;
            /** Prices */
            prices: components["schemas"]["BookPrice"][];
            best_price?: components["schemas"]["BookPrice"] | null;
            /** Consensus Price American */
            consensus_price_american?: number | null;
        };
        /** OddsResponse */
        OddsResponse: {
            /** Games */
            games: components["schemas"]["Game"][];
            /** Stale Seconds */
            stale_seconds: number;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /** Pick */
        Pick: {
            /** Id */
            id: string;
            tier: components["schemas"]["PickTier"];
            /** Game Label */
            game_label: string;
            /** Market Label */
            market_label: string;
            /** Pick Side */
            pick_side: string;
            /** Odds American */
            odds_american: number;
            /** Best Book */
            best_book?: string | null;
            /** Stake Units */
            stake_units: number;
            /** Probability Pct */
            probability_pct: number;
            /** Market Probability Pct */
            market_probability_pct: number;
            /** Edge Pct */
            edge_pct: number;
            /** Stats */
            stats?: components["schemas"]["PickStat"][];
            /** Reasoning */
            reasoning: string;
            /**
             * Agent Key
             * @default baseball-agents
             */
            agent_key: string;
            /**
             * Agent Record 30D
             * @default
             */
            agent_record_30d: string;
            /** Commence Time */
            commence_time?: string | null;
        };
        /** PickStat */
        PickStat: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * PickTier
         * @enum {string}
         */
        PickTier: "high" | "sweet" | "lean";
        /** PicksResponse */
        PicksResponse: {
            /** Picks */
            picks: components["schemas"]["Pick"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "no_picks_today";
            /**
             * Last Checked At
             * Format: date-time
             */
            last_checked_at: string;
            /** Bet Card Date */
            bet_card_date?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetcherStatus"];
                };
            };
        };
    };
    get_mlb_odds_api_odds_mlb_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OddsResponse"];
                };
            };
        };
    };
    get_mlb_props_api_props_mlb_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OddsResponse"];
                };
            };
        };
    };
    get_mlb_picks_api_picks_mlb_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicksResponse"];
                };
            };
        };
    };
    start_api_fetcher_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetcherControlResponse"];
                };
            };
        };
    };
    stop_api_fetcher_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetcherControlResponse"];
                };
            };
        };
    };
    refresh_api_refresh__event_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetcherControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
