/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/odds/{sport}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Odds */
        get: operations["get_odds_api_odds__sport__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/props/{sport}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Props */
        get: operations["get_props_api_props__sport__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picks/{sport}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Picks */
        get: operations["get_picks_api_picks__sport__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fetcher/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_fetcher_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fetcher/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_api_fetcher_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_refresh__event_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sports */
        get: operations["get_sports_api_sports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arbitrage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Arbs
         * @description Scan the cache for two-way arbitrage opportunities.
         *
         *     `books` is an optional comma-separated allowlist — only prices from
         *     these bookmaker keys are considered. Empty = all books in the cache.
         */
        get: operations["get_arbs_api_arbitrage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/low-hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Low Hold */
        get: operations["get_low_hold_api_low_hold_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/free-bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Free Bets */
        get: operations["get_free_bets_api_free_bets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ev": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ev
         * @description Scan the cache for +EV opportunities.
         *
         *     Query params:
         *       - books: csv of offered-side bookmaker keys (empty = all)
         *       - sharp_books: csv of sharp anchor books (empty = SHARP_BOOKS default)
         *       - min_ev: minimum EV percentage (ROI per $1) to include, default 1.0
         *       - max_longshot_odds: filter out offered prices above this American
         *         value; default +800 to avoid devig noise on longshots
         *       - stale_seconds: drop offered prices older than this; default 60
         *       - max_results: server-side cap after sort; default 300
         *       - tag_arb: also_in_arb flag — set false to skip arb pre-scan
         */
        get: operations["get_ev_api_ev_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coral33/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Trigger one immediate coral33 cycle (main → alt/prop) across every
         *     configured sport. Sports run in parallel; tiers within a sport run
         *     sequentially.
         */
        post: operations["refresh_api_coral33_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coral33/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_coral33_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        /** Post Settings */
        post: operations["post_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArbOpportunity */
        ArbOpportunity: {
            /** Sport Key */
            sport_key: string;
            /** Event Id */
            event_id: string;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /**
             * Commence Time
             * Format: date-time
             */
            commence_time: string;
            /**
             * Market Kind
             * @enum {string}
             */
            market_kind: "h2h" | "spreads" | "totals";
            /** Point */
            point?: number | null;
            /** Roi Pct */
            roi_pct: number;
            /** Sides */
            sides: components["schemas"]["ArbSide"][];
        };
        /** ArbResponse */
        ArbResponse: {
            /** Opportunities */
            opportunities: components["schemas"]["ArbOpportunity"][];
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /** Book Count */
            book_count: number;
        };
        /** ArbSide */
        ArbSide: {
            /** Outcome Name */
            outcome_name: string;
            /** Book */
            book: string;
            /** Price American */
            price_american: number;
            /** Point */
            point?: number | null;
            /** Stake Pct */
            stake_pct: number;
        };
        /** BookPrice */
        BookPrice: {
            /** Bookmaker Key */
            bookmaker_key: string;
            /** Price American */
            price_american: number;
            /** Point */
            point?: number | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /** Coral33RefreshResponse */
        Coral33RefreshResponse: {
            /** Status */
            status: string;
            /** Sports Refreshed */
            sports_refreshed: string[];
            /** Duration S */
            duration_s: number;
            /** Errors */
            errors: string[];
            /** Last Cycle Rows */
            last_cycle_rows: {
                [key: string]: number;
            };
        };
        /** Coral33StatusResponse */
        Coral33StatusResponse: {
            /** Running */
            running: boolean;
            /** Last Cycle At */
            last_cycle_at?: string | null;
            /** Last Cycle Rows */
            last_cycle_rows: {
                [key: string]: number;
            };
            /** Captcha Backoff Remaining S */
            captcha_backoff_remaining_s: number;
            /** Jwt Authenticated */
            jwt_authenticated: boolean;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Sports */
            sports: components["schemas"]["SportSummary"][];
            /** Top Arbs */
            top_arbs: components["schemas"]["ArbOpportunity"][];
            /** Top Picks */
            top_picks: components["schemas"]["Pick"][];
            /** Upcoming Games */
            upcoming_games: components["schemas"]["Game"][];
            fetcher: components["schemas"]["FetcherStatus"];
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
        };
        /** EVOpportunity */
        EVOpportunity: {
            /** Sport Key */
            sport_key: string;
            /** Event Id */
            event_id: string;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /**
             * Commence Time
             * Format: date-time
             */
            commence_time: string;
            /** Market Kind */
            market_kind: string;
            /** Point */
            point?: number | null;
            /** Outcome Name */
            outcome_name: string;
            /** Book */
            book: string;
            /** Offered Price American */
            offered_price_american: number;
            /** Fair Price American */
            fair_price_american: number;
            /** Fair Probability */
            fair_probability: number;
            /** Ev Pct */
            ev_pct: number;
            /** Kelly Full Pct */
            kelly_full_pct: number;
            /** Kelly Quarter Pct */
            kelly_quarter_pct: number;
            /**
             * Source
             * @enum {string}
             */
            source: "pinnacle" | "consensus";
            /** Anchor Book Count */
            anchor_book_count: number;
            /** Offered Age S */
            offered_age_s: number;
            /** Also In Arb */
            also_in_arb: boolean;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "normal" | "low";
            /**
             * Wager Type — coral33 parlay-eligibility tag.
             * NULL for every other book.
             */
            wager_type?: "straight" | "parlay" | "both" | null;
        };
        /** EVResponse */
        EVResponse: {
            /** Opportunities */
            opportunities: components["schemas"]["EVOpportunity"][];
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /** Min Ev Pct */
            min_ev_pct: number;
            /** Sharp Anchor Books */
            sharp_anchor_books: string[];
        };
        /** FetcherControlResponse */
        FetcherControlResponse: {
            /** Status */
            status: string;
            /** Tiers */
            tiers?: string[];
            /** Retry After Seconds */
            retry_after_seconds?: number | null;
            /** Event Id */
            event_id?: string | null;
            /** Polled */
            polled?: string[];
        };
        /** FetcherStatus */
        FetcherStatus: {
            /** Last Fetch At */
            last_fetch_at?: string | null;
            /** Requests Used */
            requests_used?: number | null;
            /** Requests Remaining */
            requests_remaining?: number | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Fetcher Running
             * @default false
             */
            fetcher_running: boolean;
            /** Enabled Tiers */
            enabled_tiers?: string[];
        };
        /** FreeBetLeg */
        FreeBetLeg: {
            /** Outcome Name */
            outcome_name: string;
            /** Book */
            book: string;
            /** Price American */
            price_american: number;
            /** Point */
            point?: number | null;
        };
        /** FreeBetOpportunity */
        FreeBetOpportunity: {
            /** Sport Key */
            sport_key: string;
            /** Event Id */
            event_id: string;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /**
             * Commence Time
             * Format: date-time
             */
            commence_time: string;
            /**
             * Market Kind
             * @enum {string}
             */
            market_kind: "h2h" | "spreads" | "totals";
            /** Point */
            point?: number | null;
            /** Conversion Pct */
            conversion_pct: number;
            /** Hedge Stake Per 100 */
            hedge_stake_per_100: number;
            free_leg: components["schemas"]["FreeBetLeg"];
            hedge_leg: components["schemas"]["FreeBetLeg"];
        };
        /** FreeBetResponse */
        FreeBetResponse: {
            /** Opportunities */
            opportunities: components["schemas"]["FreeBetOpportunity"][];
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /** Min Free Odds */
            min_free_odds: number;
        };
        /** Game */
        Game: {
            /** Event Id */
            event_id: string;
            /**
             * Sport Key
             * @default mlb
             */
            sport_key: string;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /**
             * Commence Time
             * Format: date-time
             */
            commence_time: string;
            /**
             * Is Live
             * @default false
             */
            is_live: boolean;
            /** Markets */
            markets: components["schemas"]["Market"][];
            /**
             * Stale Seconds
             * @default 0
             */
            stale_seconds: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LowHoldOpportunity */
        LowHoldOpportunity: {
            /** Sport Key */
            sport_key: string;
            /** Event Id */
            event_id: string;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /**
             * Commence Time
             * Format: date-time
             */
            commence_time: string;
            /**
             * Market Kind
             * @enum {string}
             */
            market_kind: "h2h" | "spreads" | "totals";
            /** Point */
            point?: number | null;
            /** Hold Pct */
            hold_pct: number;
            /** Sides */
            sides: components["schemas"]["LowHoldSide"][];
        };
        /** LowHoldResponse */
        LowHoldResponse: {
            /** Opportunities */
            opportunities: components["schemas"]["LowHoldOpportunity"][];
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /** Max Hold Pct */
            max_hold_pct: number;
        };
        /** LowHoldSide */
        LowHoldSide: {
            /** Outcome Name */
            outcome_name: string;
            /** Book */
            book: string;
            /** Price American */
            price_american: number;
            /** Point */
            point?: number | null;
        };
        /** Market */
        Market: {
            /** Market Key */
            market_key: string;
            /** Outcomes */
            outcomes: components["schemas"]["MarketOutcome"][];
        };
        /** MarketGroupModel */
        MarketGroupModel: {
            /** Label */
            label: string;
            /** Main Key */
            main_key: string;
            /** Alt Key */
            alt_key?: string | null;
            /**
             * Display
             * @default moneyline
             * @enum {string}
             */
            display: "moneyline" | "spread" | "total" | "yes_no";
        };
        /** MarketOption */
        MarketOption: {
            /** Key */
            key: string;
            /** Enabled */
            enabled: boolean;
        };
        /** MarketOutcome */
        MarketOutcome: {
            /** Outcome Name */
            outcome_name: string;
            /** Prices */
            prices: components["schemas"]["BookPrice"][];
            best_price?: components["schemas"]["BookPrice"] | null;
            /** Consensus Price American */
            consensus_price_american?: number | null;
        };
        /** OddsResponse */
        OddsResponse: {
            /** Games */
            games: components["schemas"]["Game"][];
            /** Stale Seconds */
            stale_seconds: number;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /** Pick */
        Pick: {
            /** Id */
            id: string;
            tier: components["schemas"]["PickTier"];
            /** Game Label */
            game_label: string;
            /** Market Label */
            market_label: string;
            /** Pick Side */
            pick_side: string;
            /** Odds American */
            odds_american: number;
            /** Best Book */
            best_book?: string | null;
            /** Stake Units */
            stake_units: number;
            /** Probability Pct */
            probability_pct: number;
            /** Market Probability Pct */
            market_probability_pct: number;
            /** Edge Pct */
            edge_pct: number;
            /** Stats */
            stats?: components["schemas"]["PickStat"][];
            /** Reasoning */
            reasoning: string;
            /**
             * Agent Key
             * @default baseball-agents
             */
            agent_key: string;
            /**
             * Agent Record 30D
             * @default
             */
            agent_record_30d: string;
            /** Commence Time */
            commence_time?: string | null;
            /** Sport Key */
            sport_key?: string | null;
        };
        /** PickStat */
        PickStat: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * PickTier
         * @enum {string}
         */
        PickTier: "high" | "sweet" | "lean";
        /** PicksResponse */
        PicksResponse: {
            /** Picks */
            picks: components["schemas"]["Pick"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "no_picks_today";
            /**
             * Last Checked At
             * Format: date-time
             */
            last_checked_at: string;
            /** Bet Card Date */
            bet_card_date?: string | null;
        };
        /** SettingsPayload */
        SettingsPayload: {
            /** Disabled Sports */
            disabled_sports: string[];
            /** Disabled Markets */
            disabled_markets: {
                [key: string]: string[];
            };
            /** Visible Books */
            visible_books?: string[] | null;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Disabled Sports */
            disabled_sports: string[];
            /** Disabled Markets */
            disabled_markets: {
                [key: string]: string[];
            };
            /** Sports */
            sports: components["schemas"]["SportOption"][];
            /** Visible Books */
            visible_books?: string[] | null;
        };
        /** SettingsUpdateResponse */
        SettingsUpdateResponse: {
            settings: components["schemas"]["SettingsResponse"];
            /** Reload Status */
            reload_status: string;
        };
        /** SportModel */
        SportModel: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Market Groups */
            market_groups: components["schemas"]["MarketGroupModel"][];
        };
        /** SportOption */
        SportOption: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Enabled */
            enabled: boolean;
            /** Tiers */
            tiers: components["schemas"]["TierOption"][];
        };
        /** SportSummary */
        SportSummary: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Upcoming Games */
            upcoming_games: number;
            /** Starting In 3H */
            starting_in_3h: number;
            /** Picks Today */
            picks_today: number;
            /** Bet Card Date */
            bet_card_date?: string | null;
        };
        /** SportsResponse */
        SportsResponse: {
            /** Sports */
            sports: components["schemas"]["SportModel"][];
        };
        /** TierOption */
        TierOption: {
            /** Name */
            name: string;
            /** Enabled In Config */
            enabled_in_config: boolean;
            /** Interval Seconds */
            interval_seconds: number;
            /** Markets */
            markets: components["schemas"]["MarketOption"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetcherStatus"];
                };
            };
        };
    };
    get_odds_api_odds__sport__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OddsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_props_api_props__sport__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OddsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_picks_api_picks__sport__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_fetcher_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetcherControlResponse"];
                };
            };
        };
    };
    stop_api_fetcher_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetcherControlResponse"];
                };
            };
        };
    };
    refresh_api_refresh__event_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetcherControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sports_api_sports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SportsResponse"];
                };
            };
        };
    };
    get_arbs_api_arbitrage_get: {
        parameters: {
            query?: {
                books?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_low_hold_api_low_hold_get: {
        parameters: {
            query?: {
                books?: string;
                max_hold_pct?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LowHoldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_free_bets_api_free_bets_get: {
        parameters: {
            query?: {
                books?: string;
                min_free_odds?: number;
                max_results?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreeBetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ev_api_ev_get: {
        parameters: {
            query?: {
                books?: string;
                sharp_books?: string;
                min_ev?: number;
                max_longshot_odds?: number;
                stale_seconds?: number;
                max_results?: number;
                tag_arb?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EVResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_coral33_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coral33RefreshResponse"];
                };
            };
        };
    };
    status_api_coral33_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coral33StatusResponse"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    post_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: {
                books?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
